# Generated by Django 6.1.1 on 2026-10-01 10:04

import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_path)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_feature', models.BooleanField(default=False, help_text='Designates this as the primary thumbnail for the product.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_feature', '-created_at'],
            },
        ),
    ]
